### ISSUE TITLE
Solve Pagination

### ISSUE THREAD

**Issue by Harman-B** [Harman-B/git-play#11]
Since github API proivdes 30 results per page by default. Therefore git-play app is not getting list of all repos or list of all commits.

- [x] get total number of repos.
- [x] get total number of commits.
- [ ] option to navigate to other pages in repos.
- [ ] option to navigate to other pages in commits.

**Comment by Harman-B** [comment]
the information about the total number of pages is provided in the response header.

**Link:** <https://api.github.com/user/9919/repos?page=2>; rel="next", <https://api.github.com/user/9919/repos?page=10>; rel="last"

**Comment by Harman-B** [comment]
need your assistance @devilpreet

**Comment by devilpreet** [comment]
Response header Link can be seen in Postman. Somehow, I am not able to see it in Chrome dev console. Hope you understand how it works logically, else let me know.    
For accessing the response headers via JS XMLHttpRequest use [response.headers](https://developer.mozilla.org/en-US/docs/Web/API/Response/headers)  
You can check if it returns a string or json object. For string returned, you might have to parse it for Link header.

**Comment by Harman-B** [comment]
yes, i am able to access it by `response.headers.get('Link')`

i am getting the following : `Link: https://api.github.com/user/9919/repos?page=2; rel="next", https://api.github.com/user/9919/repos?page=10; rel="last"`
yes, it is returning a string.

now do i need to use Regex to get the total number of pages?

**Comment by devilpreet** [comment]
Yes you would have to do the parsing.  
Some prebuilt solutions: https://www.abeautifulsite.net/parsing-urls-in-javascript
But Node supports it inherently. Another pointer to migrate to angular

**Comment by Harman-B** [comment]
parsed the link and then used getCommits() recursively (hope the terminology is correct) to loop over the pages.
page navigation is not required as of now as I have used a scrollable box.
