### ISSUE TITLE
add authentication to http.get request

### ISSUE THREAD

**Issue by Harman-B** [Harman-B/git-play#14]
github limits unauthenticated users to make 60 requests per hour.
https://developer.github.com/v3/#rate-limiting

authenticated user can get 5000 requests per hour

**Comment by devilpreet** [comment]
Code migrated to angular affecting this change request.

**Comment by Harman-B** [comment]
note to self:
service is making http.get request to the github API. The request should have request header which specifies user authentication.

**Comment by Harman-B** [comment]
@devilpreet 
I have passed the response header with my login credentials but the rate limiting still applies.
details in this [commit](https://github.com/Harman-B/git-play/commit/e633516fef29b8417ca185e4ecb9e7a4912f208d).

**Comment by devilpreet** [comment]
This approach would not work.
You can use octonode official github v3 api client : https://github.com/pksunkara/octonode
Or you can use Oauth as given in: https://developer.github.com/v3/auth/

For quick testing you can generate 'Personal Access token' given at same page. https://developer.github.com/v3/auth/

**Comment by Harman-B** [comment]
this [thread](https://stackoverflow.com/questions/13394077/is-there-a-way-to-increase-the-api-rate-limit-or-to-bypass-it-altogether-for-git) on stackoverflow provides some solutions. I have already implemented personal authorization token in the next [commit](https://github.com/Harman-B/git-play/commit/a1249cdd4747670f6a3512db550e47dcf18e6db7).
It still does not work.

It works when I execute the curl command using the same token!! 😄.

`curl -i https://api.github.com/?access_token=03abfa863fe6904145a8bb97df98e302290bbb8f`

Any thoughts on why it is not working in httpclient request??
