### ISSUE TITLE
Select technology stack

### ISSUE THREAD

**Issue by devilpreet** [Harman-B/git-play#2]
Initial thoughts for the technology stack and design

Logic layer to be implemented as REST API

- [x] Use Express over NodeJS

UI layers can be multiple. We start with website layer

- [x] Use JS, HTML, CSS for frontend
- [ ] JQuery framework

**Comment by devilpreet** [comment]
Found this library on which I would be creating the logic. [simple-git](https://www.npmjs.com/package/simple-git)

**Comment by devilpreet** [comment]
Initial sample Rest API created. [Postman collection](https://www.getpostman.com/collections/75b2dc488e9cb81c5884)

**Comment by Harman-B** [comment]
Learnt some basics of JQuery. I wish to stick to javascript or Typescript (as in this project as we have moved to Angular) for a while.
JQuery will seem to shorten many commands. Therefore I may not be able to retain much of Javascript.
